// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { OcrOcrPostData, OcrOcrPostError, OcrOcrPostResponse, HealthHealthGetError, HealthHealthGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Perform OCR on an image or PDF
 */
export const ocrOcrPost = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<OcrOcrPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<OcrOcrPostResponse, OcrOcrPostError, ThrowOnError>({
        ...options,
        url: '/ocr'
    });
};

/**
 * Health check endpoint
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthHealthGetResponse, HealthHealthGetError, ThrowOnError>({
        ...options,
        url: '/health'
    });
};