// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LLMOCRRequest = {
    /**
     * Filename or image data
     */
    filename?: string;
    /**
     * API key for the LLM service
     */
    api_key?: string;
    /**
     * Model name to use
     */
    model?: string;
    /**
     * LLM API endpoint URL
     */
    endpoint_url?: string;
    /**
     * Maximum tokens in response
     */
    max_tokens?: number;
    /**
     * Sampling temperature
     */
    temperature?: number;
    /**
     * Custom prompt for text extraction
     */
    prompt?: string;
};

export type OCRRequest = {
    /**
     * Filename
     */
    filename?: string;
    /**
     * Model name or path
     */
    model?: string;
    /**
     * Sampling temperature
     */
    temperature?: number;
    /**
     * Top-p sampling threshold
     */
    top_p?: number;
    /**
     * Repetition penalty
     */
    repetition_penalty?: (number | null);
    /**
     * Padding
     */
    padding?: (number | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LlmLlmOcrData = {
    body: LLMOCRRequest;
};

export type LlmLlmOcrResponse = (string);

export type LlmLlmOcrError = (HTTPValidationError);

export type OcrOcrData = {
    body: OCRRequest;
};

export type OcrOcrResponse = (string);

export type OcrOcrError = (HTTPValidationError);

export type HealthHealthResponse = (string);

export type HealthHealthError = unknown;

export type ShutdownShutdownResponse = (string);

export type ShutdownShutdownError = unknown;

export type LogsGetLogsResponse = (string);

export type LogsGetLogsError = unknown;