
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async initMenubar() : Promise<void> {
    await TAURI_INVOKE("init_menubar");
},
async showMenubarPanel() : Promise<void> {
    await TAURI_INVOKE("show_menubar_panel");
},
async hideMenubarPanel() : Promise<void> {
    await TAURI_INVOKE("hide_menubar_panel");
},
async toggleMenubarPanel() : Promise<void> {
    await TAURI_INVOKE("toggle_menubar_panel");
},
async isMenubarPanelVisible() : Promise<boolean> {
    return await TAURI_INVOKE("is_menubar_panel_visible");
},
async closeMenubarPanel() : Promise<void> {
    await TAURI_INVOKE("close_menubar_panel");
},
async initSpotlight() : Promise<void> {
    await TAURI_INVOKE("init_spotlight");
},
async showSpotlightPanel() : Promise<void> {
    await TAURI_INVOKE("show_spotlight_panel");
},
async hideSpotlightPanel() : Promise<void> {
    await TAURI_INVOKE("hide_spotlight_panel");
},
async toggleSpotlightPanel() : Promise<void> {
    await TAURI_INVOKE("toggle_spotlight_panel");
},
async isSpotlightPanelVisible() : Promise<boolean> {
    return await TAURI_INVOKE("is_spotlight_panel_visible");
},
async closeSpotlightPanel() : Promise<void> {
    await TAURI_INVOKE("close_spotlight_panel");
},
async takeScreenshot(filename: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("take_screenshot", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async performOcr(imagePath: string, detectionModel: string | null, recognitionModel: string | null, alphabet: string | null, allowedChars: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("perform_ocr", { imagePath, detectionModel, recognitionModel, alphabet, allowedChars }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async launchSidecarNougat() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_sidecar_nougat") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isSidecarNougatRunning() : Promise<boolean> {
    return await TAURI_INVOKE("is_sidecar_nougat_running");
},
async killSidecarNougat() : Promise<void> {
    await TAURI_INVOKE("kill_sidecar_nougat");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/



/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
