name: "publish_macos"

on:
  push:
    branches:
      - release

# `tauri-action` can also upload app bundles to an existing GitHub release.
# This workflow uses different actions to create and publish the release.
# `tauri-action` will only build and upload the app bundles to the specified release.

jobs:
  get-version:
    name: Get semantic versions
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.autogenerate-version.outputs.version_tag }}
      current_version_tag: ${{ steps.get-current-version.outputs.current_version_tag}}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current version
        id: get-current-version
        run: |
          CURRENT_VERSION_TAG=$(git tag --list --merged HEAD --sort=-version:refname "v*" | head -n 1)
          echo "current_version_tag=${CURRENT_VERSION_TAG}" >> $GITHUB_OUTPUT

      - name: Auto-generate future version
        id: autogenerate-version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(major)"
          minor_pattern: "(minor)"
          version_format: "${major}.${minor}.${patch}-pre${increment}"

  # create-release:
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   needs: [get-version]
  #   outputs:
  #     release_id: ${{ steps.create-github-release.outputs.result }}
  #     version_tag: ${{ needs.get-version.outputs.version_tag }}

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: create github release
  #       id: create-github-release
  #       uses: actions/github-script@v6
  #       with:
  #         script: |
  #           const { data } = await github.rest.repos.createRelease({
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             tag_name:  '${{ needs.get-version.outputs.version_tag }}',
  #             name: 'Montelimar App ${{ needs.get-version.outputs.version_tag }}',
  #             body: 'Take a look at the assets to download and install this app.',
  #             draft: true,
  #             prerelease: false
  #           })
  #           return data.id

  build-tauri:
    needs: [get-version]
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cache bun
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "src-python/.python-version"

      - name: "Install the project"
        run: |
          cd src-python
          uv venv
          source .venv/bin/activate
          uv sync
          uv pip install --system hatch

      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: install frontend dependencies
        run: bun install # change this to npm, pnpm or bun depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ needs.get-version.outputs.version_tag }}
          releaseName: 'Montelimar App v${{ needs.get-version.outputs.version_tag }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

  # publish-release:
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   needs: [build-tauri]

  #   steps:
  #     - name: publish release
  #       id: publish-release
  #       uses: actions/github-script@v6
  #       env:
  #         release_id: ${{ needs.build-tauri.outputs.release_id }}
  #       with:
  #         script: |
  #           github.rest.repos.updateRelease({
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             release_id: process.env.release_id,
  #             draft: false,
  #             prerelease: false
  #           })